---
archives:
  - name_template: 'epinio-{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64
    format: binary
    format_overrides:
      - goos: windows
        format: zip

before:
  hooks:
    - go mod download

builds:
  - id: epinio-installer
    main: ./cmd/epinio-installer/main.go
    binary: epinio-installer
    ldflags:
      - -w -s
      - -X "github.com/epinio/installer/internal/version.Version={{ .Tag }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm

changelog:
  ## Delegate Changelog to release-drafter
  skip: true

env:
  - CGO_ENABLED=0

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  -
    # ID of the image, needed if you want to filter by it later on (e.g. on custom publishers).
    id: epinio-installer-noassets

    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    # IDs to filter the binaries/packages.
    ids:
    - epinio-installer

    # Templates of the Docker image names.
    image_templates:
    - "ghcr.io/epinio/epinio-installer-noassets:{{ .Tag }}"
    - "ghcr.io/epinio/epinio-installer-noassets:latest"

    # Skips the docker push.
    #skip_push: "true"

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile

    use: docker

    # Template of the docker build flags.
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title=epinio-{{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/epinio/installer"
    - "--build-arg=HELM_VERSION={{.Env.HELM_VERSION}}"
    - "--build-arg=HELM_CHECKSUM={{.Env.HELM_CHECKSUM}}"
    - "--build-arg=KUBECTL_VERSION={{.Env.KUBECTL_VERSION}}"
    - "--build-arg=KUBECTL_CHECKSUM={{.Env.KUBECTL_CHECKSUM}}"
    - "--build-arg=DIST_BINARY=epinio-installer"
    - "--platform=linux/amd64"
