name: Unit tests

on:
  workflow_run:
    workflows: ["Linting"]
    types: 
      - completed
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unit tests
        run:
          go test ./...
