name: Unit tests

on:
  workflow_run:
    workflows: ["Linting"]
    types: 
      - completed

env:
  SETUP_GO_VERSION: '^1.17.2'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ginkgo Test Framework
        run: go install github.com/onsi/ginkgo/ginkgo@v1.16.2
      - name: Unit tests
        run:
          ginkgo -r -p race -failOnPending internal/.
